parameters:
    dacorp.user_manager.class: Dacorp\ExtraBundle\Services\UserManager
    dacorp.session_manager.class: Dacorp\ExtraBundle\Services\SessionManager
    dacorp.yml_file_manager_service.class: Dacorp\ExtraBundle\Services\YmlFileManager

services:
    dacorp.user.manager:
        class: %dacorp.user_manager.class%
#        arguments: ["@service_container", "@doctrine.orm.entity_manager", "@session"]
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer","@fos_user.entity_manager", %fos_user.model.user.class%]

    dacorp.manager.session:
        class: %dacorp.session_manager.class%
        arguments: ["@session", "@service_container", "@doctrine.orm.entity_manager"]

    dacorp.manager.yml_file:
        class: %dacorp.yml_file_manager_service.class%
        arguments: ["%kernel.root_dir%/../app/data_fixtures"]
